services:
  - type: web
    name: spa-parking-api
    env: node
    plan: free # Sử dụng gói miễn phí
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: spa-parking-db
          property: connectionString

databases:
  - name: spa-parking-db
    plan: free # Sử dụng gói miễn phí
    databaseName: spa_parking
    user: spa_user
